### ISSUE TITLE
request for release

### ISSUE THREAD

**Issue by shimwell** [pshriwise/double-down#4]
Wondering if a Github release could be made for this nice package.

This would help with the conda build scripts that tend to point to a url with a .tar.gz from the releases url like this

```
url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
```

**Comment by pshriwise** [comment]
There are a couple of things I'd like to take care of before a release, but yes! I can prioritize that in the near future.

**Comment by pshriwise** [comment]
Done! https://github.com/pshriwise/double-down/releases/tag/v1.0.0
